name: Coverage

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  coverage:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - run: pip install nox==2022.11.21 poetry==1.4.0
      - run: nox --python 3.11 --sessions tests coverage
        env:
          CODECOV_TOKEN: ${{secrets.CODECOV_TOKEN}}
