name: Coverage

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  coverage:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: "3.9"
      - run: pip install poetry==1.1.10
      - run: pip install nox==2021.6.12
      - run: nox --sessions tests-3.9 coverage
        env:
          CODECOV_TOKEN: ${{secrets.CODECOV_TOKEN}}
