name: Coverage

on: push

jobs:
  coverage:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: "3.9"
      - run: pip install poetry==1.1.6
      - run: pip install nox==2020.12.31
      - run: nox --sessions tests-3.9 coverage
        env:
          CODECOV_TOKEN: ${{secrets.CODECOV_TOKEN}}
